### ISSUE TITLE
ShowOnMap function doesn't handle åäöÅÄÖ

### ISSUE THREAD

**Issue by tomaseketorp** [Lundalogik/LimeBootstrap#62]
When using version1.7, å, ä, ö is replaced by spaces when using the showonmap-function (look up an address on Google Maps)

**Comment by ThinkFlipp** [comment]
Good error report!
The bug is situated here: https://github.com/Lundalogik/LimeBootstrap/blob/master/system/js/lbs.bindings.js#L132

We need to add to URL-encode, the data before adding it to the URL, http://stackoverflow.com/questions/332872/encode-url-in-javascript

This is a super easy fix and should be included in 1.8 or even in a 1.7.1-release (NOTE: our updater doesn't support that kind of versioning though...)

**Comment by ThinkFlipp** [comment]
There is now a PL for a fix, here : https://github.com/Lundalogik/LimeBootstrap/pull/63

Some one should check the code and then merge
